import com.uncia.unciadroolsemicalculation.model.Participant;
global com.uncia.unciadroolsemicalculation.model.Rate rate;

dialect "mvel"


rule "Checking Credit Score less than 550"
 when
  Participant(creditScore < 600)
 then
  rate.setLoanStatus("Rejected");
  rate.setLoanRate(999);
end

rule "Checking Credit Score less than 650"
 when
  Participant((creditScore < 650 && creditScore >= 550))
 then
  rate.setLoanStatus("Approved");
  rate.setLoanRate(12);
end

rule "Checking Credit Score less than 750"
 when
  Participant((creditScore < 750 && creditScore >= 650))
 then
  rate.setLoanStatus("Approved");
  rate.setLoanRate(10);
end

rule "Checking Credit Score greater than 750"
 when
  Participant(creditScore >= 750)
 then
  rate.setLoanStatus("Approved");
  rate.setLoanRate(9);
end